# Generated by Django 3.2.9 on 2021-11-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place_id', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('picture', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('website', models.TextField(null=True)),
                ('star', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag', to='line_bot.tag')),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
